### ISSUE TITLE
Problem with $my_creds

### ISSUE THREAD

**Issue by nekolaadam** [rodalton/watson-functions#1]
Hello,

I followed the instructions and watched the video made by you and I am still having some issues. At the end, when I have everything set up, exactly as you have, Watson Discovery still doesn´t respond me in the Watson Assistant Dialog. I think, that it is due to the $my_creds variable, because instead of the "user" and "password" authentications the API keys are now used everywhere. Could this be the problem? If yes, how can I modify the my_creds.json in order to make the authentication into the Functions?

If needed, I can provide you with screenshots.

Thank you very much! This thread was more than helpful and I hope I can make it work with your help.

**Comment by rodalton** [comment]
So you're testing your Watson Assistant Dialog using the 'Try it out' pane, but when a node that should call Watson Discovery via Cloud Functions is invoked, you get no response? Do you see any error in Watson Assistant? If there was an issue with your Cloud Functions creds, you'd see an error message returned. If there's no error returned, the issue might be in you Cloud Function call Discovery. Maybe check you have the right credentials (for Discovery) there? Test if you can invoke your Action using the 'Invoke' button and whether this works OK. 

Would be happy to join you on a call/webex to work this through.

**Comment by nekolaadam** [comment]
Thank you so much for your swift reply! Yes, you are correct. I do not receive any error message in the dialog that could suggest that I have problem with the $my_creds variable. Actually, when I tried implementing the skills in the actual assistant and asked the bot about anything that should have invoked the function to call the Discovey, I got a reply: "null", which might suggest some issues, that the function is trying to contact the Discovery but is unable to return the answer. When I ask the bot in "Try it out" panel, I receive just an empty space.

I tried invoking a response in the function, as you did in your video, by writting an example of a query into the "input" parameter and it worked.

If it would be okay with you, I would be more than happy to settle this matter over a call/webex with you as well. The problem is that I am doing this chatbot for an interview into the IBM which is in 2 hours so I have only 1 hour to resolve this and I expect, that you do not have time right now because you are in work or doing something.

If you do have time right now though, would you send me the link for the session? If not, that´s okay. :) I will gladly resolve this issue even after the interview, but then it is just for the stake of making it work and I do not want to waste your time.

Thank you again for your time and help!

**Comment by nekolaadam** [comment]
Oh, I am terribly sorry. I just found the error message.

![image](https://user-images.githubusercontent.com/45903941/50086549-b960e700-01fd-11e9-8cb6-5f52ee7ecfab.png)

**Comment by rodalton** [comment]
OK, looks like you don't have a $my_creds variable set. I can join you on a call if there's a way I can DM/PM you my details.

**Comment by nekolaadam** [comment]
I am sorry again. The screenshot before was a mistake. I do not know how, but the $my_creds variable deleted itself. The official error message is the new one stating - Direct CloudFunctions calls are not supported on this platform.

I am kind of new to this whole bluemix concept. Is there any way how to make this work?

**Comment by rodalton** [comment]
Thanks, based on the new image above, it would seem your Watson Assistant instance is not running in the US South (Dallas) region? Cloud Function calls from Watson Assistant are supported from US South only.

**Comment by rodalton** [comment]
Sorry, I stand corrected, Cloud Function calls can also be made from a Watson Assistant instance running in Frankfurt. See 'Location restrictions' here https://console.bluemix.net/docs/services/assistant/dialog-actions.html#dialog-actions

**Comment by nekolaadam** [comment]
Oh I see, that´s why you were mentioning it in the video. I live in Czech Republic and therefore I thought that it only allows me to create a "Cloud Foundry Space" in London (that is what I have), because I was unable to change it. I will try to look at it if I can change into Franktfurt. :) Thank you so so much! I do not know what would I do without you.

**Comment by rodalton** [comment]
No problem, you're welcome. Best of luck with the interview! Hopefully you've learnt a little about Watson Assistant, Cloud Functions & Watson Discovery that'll help with any questions that might arise :) Be sure to ping if you join IBM, it's a great place to work!
